### ISSUE TITLE
Function re-exported from the `igraph` package will obtain a new argument in igraph 1.3.0

### ISSUE THREAD

**Issue by ntamas** [asalavaty/influential#1]
The `influential` package is re-exporting the `betweenness` function from `igraph` along with some documentation. This function in `igraph` will gain a new argument named `cutoff` in the next version, and R's CRAN checks will complain that the `cutoff` argument is not documented in your package.

In particular, I think that re-exporting functions as-is should be avoided because the CRAN checks will break on your package every time the re-exported function gains a new argument in the upstream package where it is re-exported from. Consider wrapping the original function instead, i.e.:

```
betweenness <- function(graph, v = V(graph), directed = TRUE, ...) {
    igraph::betweenness(graph, v, directed=directed, ...)
}
```

This way you only need to document the arguments that are explicitly listed in _your_ function signature and we are free to add new arguments in `igraph` without breaking the CRAN checks for you.

**Comment by asalavaty** [comment]
@ntamas Thanks for letting me know. I will fix that in the next release of the influential R package.
