### ISSUE TITLE
Error in as.igraph.vs(graph, v) : could not find function "as.igraph.vs"

### ISSUE THREAD

**Issue by KarakulakTulay** [asalavaty/influential#3]
Hi Adrian, 
Thank you for this cool package! I want to use influential to calculate the important nodes in a protein interaction network. My code is the following: 
 
**create graph from data frame**
```
edges  <-  subset_protein_network_data_frame
g <- influential::graph_from_data_frame(edges, directed = FALSE)
```

**take node names**
`GraphNodes <- V(g)`

**calculate IVI** 
```
My.Nodes.IVI <- ivi(graph = g, vertices = GraphNodes, 
                       weights = NULL, directed = FALSE, mode = "all",
                       loops = TRUE, d = 3, scaled = TRUE)
```

However, I am getting the following error in the ivi() step:
_Error in as.igraph.vs(graph, v) : could not find function "as.igraph.vs"_

I have igraph 1.5.0 and influential 2.2.7.0009 version. 

Do you know what would be the reason and how I could solve it? I'd appreciate your help. 

Best, 
Tülay

**Comment by asalavaty** [comment]
> Hi Adrian, 
> 
> Thank you for this cool package! I want to use influential to calculate the important nodes in a protein interaction network. My code is the following: 
> 
>  
> 
> **create graph from data frame**
> 
> ```
> 
> edges  <-  subset_protein_network_data_frame
> 
> g <- influential::graph_from_data_frame(edges, directed = FALSE)
> 
> ```
> 
> 
> 
> **take node names**
> 
> `GraphNodes <- V(g)`
> 
> 
> 
> **calculate IVI** 
> 
> ```
> 
> My.Nodes.IVI <- ivi(graph = g, vertices = GraphNodes, 
> 
>                        weights = NULL, directed = FALSE, mode = "all",
> 
>                        loops = TRUE, d = 3, scaled = TRUE)
> 
> ```
> 
> 
> 
> However, I am getting the following error in the ivi() step:
> 
> _Error in as.igraph.vs(graph, v) : could not find function "as.igraph.vs"_
> 
> 
> 
> I have igraph 1.5.0 and influential 2.2.7.0009 version. 
> 
> 
> 
> Do you know what would be the reason and how I could solve it? I'd appreciate your help. 
> 
> 
> 
> Best, 
> 
> Tülay

Hi Tulay,

Thanks for your message. The problem arises from the incompatibility between the updates of the influential and igraph packages. To resolve the issue please follow the steps below:

1. Remove both the influential and igraph packages using the remove.packages() function. For example, remove.packages("influential")

2. Restart R and R studio (close and reopen)

3. Re-install the influential R package, either its CRAN or its developmental version.

Hopefully, it resolves the issue. Please let me know if you faced any other issues or have any questions.

Cheers,
Adrian

**Comment by KarakulakTulay** [comment]
Thank you for the quick response Adrian! 
I followed the steps you have described. Unfortunately, I am still getting the same error. I installed CRAN and developmental versions separately to try out both of them, but both gives the the same error. The igraph version that is installed while installing influential package is again 1.5.0. 
Please let me know if you need more info. 
Best wishes, 
Tülay

**Comment by KarakulakTulay** [comment]
Dear Adrian, 

Even though I closed and reopened the RStudio, looks like it did not renew the R session. **.rs.restartR()** solved the issue. ivi() function works smoothly. Once again, thank you for your help!

Cheers,
Tülay

**Comment by asalavaty** [comment]
> Dear Adrian,
> 
> Even though I closed and reopened the RStudio, looks like it did not renew the R session. **.rs.restartR()** solved the issue. ivi() function works smoothly. Once again, thank you for your help!
> 
> Cheers, Tülay

Dear Tülay,

I am happy your issue is resolved. 

To be more specific, the issue originated from the `degree` function of the graph package. The igraph recently updated its `as.igraph.vs` function, which is recruited in the calculation of the Degree centrality, to `as_igraph_vs `. Thus, because some packages other than influential also use igraph package and occasionally require you to update the igraph package, that had resulted in the incompatibility between the influential and igraph packages.

Cheers,
Adrian
