### ISSUE TITLE
Parallelize SIRIR ?

### ISSUE THREAD

**Issue by binonteji** [asalavaty/influential#4]
Hi there, it is a wonderful library. 

Could you help me to parallelize the SIRIR() function ?  I am trying to get the influential node from a large network. 

Thanks in Advance!

**Comment by asalavaty** [comment]
> Hi there, it is a wonderful library.
> 
> Could you help me to parallelize the SIRIR() function ? I am trying to get the influential node from a large network.
> 
> Thanks in Advance!

Dear @binonteji 

Thanks for reaching out. As requested, I converted the `sirir` function to a parallelized and vectorized format which is much faster than its previous version. Please simply follow the following steps to use the new version of the SIRIR function.

1. Remove the influential package by running:
`remove.packages('influential')`
2. Install the new developmental version of the package by running:
`## install.packages("devtools") 
devtools::install_github("asalavaty/influential", build_vignettes = TRUE)`
3. Restart your R session by running:
`.rs.restartR()`

Two additional arguments are added to the function, `ncores` and `verbose`. You may set the verbose to `TRUE` to check the progress of your job.

**Note:** The argument `no.sim` has a considerable impact on the computation time. If you are working with large networks you may consider setting this argument to lower values than its default. For example, setting `no.sim = 100`.

### Recommendation
The SIRIR function evaluates the structural impact of the removal of nodes on the network and is purposed majorly as a ground truth for evaluating the functioning of different centrality measures. The SIRIR function can also be used as an additional method for benchmarking experiments for the evaluation of several centrality measures. However, in case you seek to evaluate the **influence** of network nodes I recommend you to use the `ivi` function for calculating the Integrated Value of Influence of nodes. [Read further about the IVI algorithm](https://doi.org/10.1016/j.patter.2020.100052).

Please don't hesitate to ask if you have any other questions.

Cheers,
Adrian
