### ISSUE TITLE
Error encountered in SIRIR and IVI functions

### ISSUE THREAD

**Issue by binonteji** [asalavaty/influential#5]
Hi there, I am encountering the errors while executing SIRIR and IVI functions: 

**1. Error in igraph::sir(graph = graph, beta = beta, gamma = gamma, no.sim = no.sim) : 
  At core/misc/sir.c:146 : SIR model only works with simple graphs. Invalid value

2. Error in socketConnection("localhost", port = port, server = TRUE, blocking = TRUE,  : 
  all connections are in use.** 

Please help! 

Thanks in advance.

**Comment by asalavaty** [comment]
> 

Hi @binonteji ,

Thanks for your message. Please see below the reasons for what has happened and how to resolve these issues.

1. Some functions of the influential such as `sirir` use `igraph::sir()` function in their core. The error message you encountered suggests that the function `igraph::sir()` in R is expecting a simple graph as input, but the graph you provided is not considered a simple graph.

In graph theory, a simple graph is an undirected graph with no self-loops or multiple edges between the same pair of vertices. It seems that the graph you are using violates one or more of these conditions, causing the error.

To resolve this issue, you can try one of the following approaches:

- Simplify the graph: If your graph contains self-loops or multiple edges between the same vertices, you can simplify it using the `simplify()` function from the **igraph** package. For example:
`simplified_graph <- igraph::simplify(graph)`

- Create a simple graph: If your graph represents a more complex structure that cannot be simplified, you might need to convert it into a simple graph. This process depends on the specific characteristics of your graph and your desired outcome. You could consider removing self-loops, merging multiple edges, or transforming the graph in a way that satisfies the requirements of a simple graph.

- Check your graph data: Ensure that the data you are using to create the graph is correct and follows the desired format. Make sure there are no inconsistencies or errors in the input data that could lead to the creation of a non-simple graph.

2. The `IVI` function of the influential package now uses parallel processing to speed up the computation. The error message you mentioned ("_Error in socketConnection: all connections are in use_") can be related to the use of parallel processing and the `%dopar%` operator from the **foreach** package which is recruited by `IVI`.

To address this issue, you can try the following steps:

- Limit the number of parallel workers: Reduce the number of parallel workers by setting the argument `ncores` of the `ivi` function. For example:
`ivi(graph, ncores = 2)` # Note that the lower the number of cores the higher the computation time.
By default, the argument `ncores` uses all the cores of your system minus 1, and if you are doing other heavy tasks on your system or have multiple concurrent R sessions you would encounter the error.

- Close connections explicitly: Ensure that you explicitly close connections within your loop or after completing the parallel computations. You can use the close() function to close the connections. For example:
`closeAllConnections()`

I hope this helps.

Cheers,
Adrian
