### ISSUE TITLE
Error with igraph 1.6.0 release candidate

### ISSUE THREAD

**Issue by krlmlr** [asalavaty/influential#6]
This package fails its checks for the release candidate for igraph 1.6.0. See <https://github.com/igraph/rigraph/blob/main/revdep/problems.md> for details.

Is this a problem in your package? Should we be doing things differently?

We're planning to release igraph 1.6.0 early December. This should give us at least until late mid-December, perhaps early January, to resolve this and keep CRAN happy at the same time. Thank you for your help!

Tracker: https://github.com/igraph/rigraph/issues/968.

**Comment by asalavaty** [comment]
I just submitted an updated version of the package to CRAN. Hopefully, this will resolve the issue and incompatibilities. Please let me know if there is any other problem.

**Comment by krlmlr** [comment]
Thanks. It seems we're still seeing failures, even with the updated package. Can you please double-check?

**Comment by krlmlr** [comment]
Friendly reminder: we're releasing igraph 1.6.0 in early December.

**Comment by asalavaty** [comment]
> Friendly reminder: we're releasing igraph 1.6.0 in early December.

I double-checked the R functions and the warning notes from the reverse dependency checks but it doesn't seem to be a problem in my R function scripts.

Here's what I think is the root of the warning:

Warning:
"""
Codoc mismatches from documentation object 'graph_from_incidence_matrix':
graph_from_incidence_matrix
  Code: function(...)
  Docs: function(incidence, directed = FALSE, mode = c("all", "out",
                 "in", "total"), multiple = FALSE, weighted = NULL,
                 add.names = NULL)
  Argument names in code not in docs:
    ...
  Argument names in docs not in code:
    incidence directed mode multiple weighted add.names
  Mismatches in argument names:
    Position: 1 Code: ... Docs: incidence
"""

graph_from_incidence_matrix is one of the functions of the R package influential which is actually directing to the same function in igraph. The arguments described in the doc are the same as the ones described in the graph function. However, in your package you have the function from_incidence_matrix(...) as well which is used for the same purpose but its only argument is `...`. And, though I am referring the function in my package to igraph::graph_from_incidence_matrix I have no idea why it still uses the from_incidence_matrix for reverse dependency check.

Overall, I think there shouldn't be any problem or incompatibility.

**Comment by krlmlr** [comment]
Thanks. I quickly reviewed the code. I understand you want to make `graph_from_incidence_matrix()` available to users that attach your package without necessarily attaching igraph. The current implementation uses the definition of `graph_from_incidence_matrix()` at build/installation time of your package. This means we can't change our implementation without breaking your package. I'll submit a PR.

**Comment by krlmlr** [comment]
Sent igraph 1.6.0 to CRAN. Tracker for 2.0.0: https://github.com/igraph/rigraph/issues/989.

**Comment by krlmlr** [comment]
Thanks for pushing influential to CRAN!

**Comment by asalavaty** [comment]
My pleasure!
